version: "3.8"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/real-estate-price-prediction/app
      - ./ml:/real-estate-price-prediction/ml
      - ./config:/real-estate-price-prediction/config
      - ./Makefile:/real-estate-price-prediction/Makefile
      - ./luigi.toml:/real-estate-price-prediction/luigi.toml
    working_dir: /real-estate-price-prediction
