version: "3.8"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/real-estate-price-prediction/app
      - ./ml/model/:/real-estate-price-prediction/ml/model
      - ./ml/data/examples/:/real-estate-price-prediction/ml/data/examples
    working_dir: /real-estate-price-prediction
