version: "3.8"

services:
  app:
    image: app:v1
    container_name: app
    build:
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/real-estate-price-prediction/app
      - ./ml:/real-estate-price-prediction/ml
      - ./config:/real-estate-price-prediction/config
      - ./Makefile:/real-estate-price-prediction/Makefile
    working_dir: /real-estate-price-prediction
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./ml/data/db:/var/lib/postgresql/data
      - ./ml/data/raw:/real-estate-price-prediction/ml/data/raw
    working_dir: /real-estate-price-prediction
